import React from "react";
import Head from "next/head";
import ClientOnly from "@components/ClientOnly";
import ImageApp from "@components/ImageApp";

export default function Home() {
	return (
		<>
			<Head>
				<title>Next CRUD Demo</title>
				<meta name="description" content="Generated by create-t3-app" />
			</Head>
			<main className="container h-full overflow-auto bg-primary py-4 max-xs:p-[5vw]">
				<ClientOnly>
					<ImageApp />
				</ClientOnly>
			</main>
		</>
	);
}
