import React from "react";
import Head from "next/head";
import ImageControl from "@components/ImageControl";
import ImageGrid from "@components/ImageGrid";
/// import { api } from "@utils/api.ts";

export default function Home() {
	return (
		<>
			<Head>
				<title>Next CRUD Demo</title>
				<meta name="description" content="Generated by create-t3-app" />
			</Head>
			<main className="container py-4">
				<ImageControl />
				<ImageGrid
					images={[
						{ id: "1", name: "Image 1", url: "https://picsum.photos/seed/picsum-1/640/320" },
						{ id: "2", name: "Image 2", url: "https://picsum.photos/seed/picsum2/640/320" },
						{ id: "3", name: "Image 3", url: "https://picsum.photos/seed/picsum03/640/320" },
						{ id: "4", name: "Image 4", url: "https://picsum.photos/seed/picsum4/640/320" },
					]}
				/>
			</main>
		</>
	);
}
