import React from "react";
import Head from "next/head";
import ImageControl from "@components/ImageControl";
import ImageGrid from "@components/ImageGrid";
/// import { api } from "@utils/api.ts";

const images = [
	{ id: "1", name: "Image 1", url: "https://picsum.photos/seed/picsum-1/640/320" },
	{ id: "2", name: "Image 2", url: "https://picsum.photos/seed/picsum2/640/320" },
	{ id: "3", name: "this is Image 3", url: "https://picsum.photos/seed/picsum03/640/320" },
	{ id: "4", name: "Image 4", url: "https://picsum.photos/seed/picsum4/640/320" },
];

export default function Home() {
	const [imageFilter, setImageFilter] = React.useState("");

	return (
		<>
			<Head>
				<title>Next CRUD Demo</title>
				<meta name="description" content="Generated by create-t3-app" />
			</Head>
			<main className="container h-full overflow-auto bg-primary py-4 max-xs:p-[5vw]">
				<ImageControl imageFilter={imageFilter} setImageFilter={setImageFilter} />
				<ImageGrid images={images.filter(({ name }) => name.toLowerCase().includes(imageFilter.toLowerCase()))} />
			</main>
		</>
	);
}
